services:
  postgres:
    container_name: somadhan-db
    image: pgvector/pgvector:pg16 
    environment:
      POSTGRES_USER: somadhan
      POSTGRES_PASSWORD: somadhan
      POSTGRES_DB: somadhan
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped