global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'product-search-api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Mac/Windows Docker
    metrics_path: '/metrics'
    scheme: 'http' 